#!/usr/bin/env bash
# dssh-whisper-api installer — lightweight, API-only path.
#
# Drops a single Python "shim" plus a small CLI wrapper that talks to
# OpenRouter's Whisper Large V3 Turbo audio endpoint.  Used when you
# don't want a 466 MB local model + venv + systemd daemon — the cloud
# does the work and the server-side footprint is ~30 KB.
#
# Run after cloning the DSSH repo:
#   bash tools/install_whisper_api.sh
#
# Or one-shot from anywhere on a Linux host with network:
#   curl -fsSL https://raw.githubusercontent.com/Fishason/DSSH/main/tools/install_whisper_api.sh | bash
#
# (The piped-curl path requires the shim file to be downloadable from
# the same release tag — handled at the bottom of this script.)
#
# Requirements:  python3, curl, systemd (optional, only if you'll later
#                upgrade to dual track via install_whisper_dual.sh)
set -euo pipefail

INSTALL_DIR="$HOME/.local/share/dssh-whisper"
CFG_DIR="$HOME/.config/dssh-whisper"
BIN_DIR="$HOME/.local/bin"

if [ -n "${BASH_SOURCE[0]:-}" ] && [ -f "${BASH_SOURCE[0]}" ]; then
    SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
else
    SCRIPT_DIR=""
fi

c()   { printf '\033[%sm%s\033[0m\n' "$1" "$2"; }
log() { c '36' "▶ $*"; }
ok()  { c '32' "✓ $*"; }
err() { c '31' "✗ $*" >&2; }

# ─────────────────────────────────────────────────────────────────────
# Phase 1 — prerequisites (just python3)
# ─────────────────────────────────────────────────────────────────────
log "checking prerequisites..."
if ! command -v python3 >/dev/null 2>&1; then
    err "python3 is required but not found."
    err "  Ubuntu / Debian:  sudo apt install -y python3"
    exit 1
fi
ok "python3 $(python3 -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")')"

# ─────────────────────────────────────────────────────────────────────
# Phase 2 — drop shim + CLI wrapper
# ─────────────────────────────────────────────────────────────────────
mkdir -p "$INSTALL_DIR" "$CFG_DIR" "$BIN_DIR"

if [ -n "$SCRIPT_DIR" ] && [ -f "$SCRIPT_DIR/whisper_shim.py" ]; then
    install -m 0755 "$SCRIPT_DIR/whisper_shim.py" "$INSTALL_DIR/whisper_shim.py"
else
    err "Cannot locate whisper_shim.py next to this installer."
    err "  Run from a DSSH repo clone:"
    err "    git clone https://github.com/Fishason/DSSH /tmp/DSSH"
    err "    bash /tmp/DSSH/tools/install_whisper_api.sh"
    exit 1
fi

# CLI wrapper — pure bash, dispatches to systemctl when a daemon exists,
# otherwise gracefully reports "API-only mode".
cat > "$BIN_DIR/dssh-whisper" <<'WRAPPER'
#!/usr/bin/env bash
# Generated by install_whisper_api.sh / install_whisper_dual.sh.
# Manages the dssh-whisper voice-input track configuration plus the
# (optional) local self-hosted whisper.cpp daemon.
SVC=dssh-whisper.service
SVC_FILE="$HOME/.config/systemd/user/$SVC"
CFG="$HOME/.config/dssh-whisper"
TRACK_FILE="$CFG/track"
KEY_FILE="$CFG/api-key"

has_daemon()  { [ -f "$SVC_FILE" ]; }
cur_track()   { [ -f "$TRACK_FILE" ] && cat "$TRACK_FILE" || echo api; }
write_track() { mkdir -p "$CFG"; echo "$1" > "$TRACK_FILE"; }

ensure_daemon_for_local() {
    if [ "$1" = local ] && has_daemon; then
        if ! systemctl --user is-active --quiet "$SVC"; then
            echo "  starting local daemon..."
            systemctl --user start "$SVC" || {
                echo "  warning: could not start $SVC; check 'dssh-whisper logs'"
                return 1
            }
        fi
    elif [ "$1" = local ] && ! has_daemon; then
        echo "  warning: local track requires the dual install (install_whisper_dual.sh)."
        echo "           the API-only install has no local daemon to start."
    fi
}

case "${1:-status}" in
    start)
        if has_daemon; then systemctl --user start "$SVC"
        else echo "API-only install: no daemon to start (track=api uses OpenRouter)."; fi ;;
    stop|close)
        if has_daemon; then systemctl --user stop "$SVC"
        else echo "API-only install: no daemon to stop."; fi ;;
    restart)
        if has_daemon; then systemctl --user restart "$SVC"
        else echo "API-only install: no daemon to restart."; fi ;;
    status)
        echo "active track: $(cur_track)"
        if has_daemon; then
            echo "---"
            systemctl --user status "$SVC" --no-pager 2>&1 | head -10
        else
            echo "(API-only install — no local daemon)"
        fi
        if [ "$(cur_track)" = api ]; then
            if [ -f "$KEY_FILE" ]; then echo "api-key:  ✓ $KEY_FILE"
            else echo "api-key:  ✗ MISSING ($KEY_FILE)"; fi
        fi ;;
    switch)
        cur=$(cur_track)
        new="${2:-$([ "$cur" = api ] && echo local || echo api)}"
        case "$new" in api|local) ;; *) echo "usage: dssh-whisper switch [api|local]"; exit 1 ;; esac
        if [ "$new" = api ] && [ ! -f "$KEY_FILE" ]; then
            echo "✗ track=api requires an API key at $KEY_FILE"
            echo "  re-run install or write the key manually:  echo \"sk-or-...\" > $KEY_FILE && chmod 0600 $KEY_FILE"
            exit 1
        fi
        write_track "$new"
        echo "→ track: $new"
        ensure_daemon_for_local "$new" ;;
    logs)
        if has_daemon; then shift; journalctl --user -u "$SVC" -n 50 --no-pager "$@"
        else echo "API-only install: no daemon logs."; fi ;;
    uninstall)
        if has_daemon; then systemctl --user disable --now "$SVC" 2>/dev/null || true; fi
        rm -rf "$HOME/.local/share/dssh-whisper" \
               "$HOME/.config/dssh-whisper" \
               "$SVC_FILE" \
               "$HOME/.local/bin/dssh-whisper" \
               "$HOME/.local/bin/dssh-whisper-shim" \
               /tmp/dssh-whisper.sock
        if has_daemon; then systemctl --user daemon-reload; fi
        echo "✓ dssh-whisper uninstalled" ;;
    *)
        cat <<HELP
usage: dssh-whisper {start|stop|restart|status|switch|logs|uninstall}

  start      start the local daemon (dual install only; no-op for api-only)
  stop|close stop the local daemon
  restart    restart the local daemon
  status     show active track + daemon status + api-key presence
  switch     toggle / select track:  dssh-whisper switch [api|local]
  logs       tail the local daemon logs
  uninstall  remove all dssh-whisper files (irreversible)

The active "track" is one of:
  api    POST audio to OpenRouter Whisper Large V3 Turbo (~1 s, \$0.04/hr)
  local  forward to /tmp/dssh-whisper.sock (self-hosted whisper.cpp daemon)
HELP
        exit 1 ;;
esac
WRAPPER
chmod +x "$BIN_DIR/dssh-whisper"

ln -sf "$INSTALL_DIR/whisper_shim.py" "$BIN_DIR/dssh-whisper-shim"

# ─────────────────────────────────────────────────────────────────────
# Phase 3 — track config + API key
# ─────────────────────────────────────────────────────────────────────
log "writing track config..."
echo "api" > "$CFG_DIR/track"

if [ ! -f "$CFG_DIR/api-key" ]; then
    if [ -n "${OPENROUTER_API_KEY:-}" ]; then
        # Picked up from env — useful for non-interactive installs (CI).
        printf '%s\n' "$OPENROUTER_API_KEY" > "$CFG_DIR/api-key"
        chmod 0600 "$CFG_DIR/api-key"
        ok "api-key written from \$OPENROUTER_API_KEY"
    elif [ -t 0 ]; then
        echo
        echo "Need your OpenRouter API key (https://openrouter.ai/settings/keys)."
        echo "It looks like:  sk-or-v1-...."
        printf "Paste your key (or empty to skip): "
        read -r KEY
        if [ -n "$KEY" ]; then
            printf '%s\n' "$KEY" > "$CFG_DIR/api-key"
            chmod 0600 "$CFG_DIR/api-key"
            ok "api-key saved at $CFG_DIR/api-key (chmod 0600)"
        else
            err "no key provided; voice input will fail until you write one:"
            err "    echo 'sk-or-v1-...' > $CFG_DIR/api-key && chmod 0600 $CFG_DIR/api-key"
        fi
    else
        # Piped install with no env var and no tty — leave it for the user.
        err "no \$OPENROUTER_API_KEY in env and no terminal to prompt."
        err "    write your key manually:"
        err "      echo 'sk-or-v1-...' > $CFG_DIR/api-key && chmod 0600 $CFG_DIR/api-key"
    fi
else
    ok "api-key already present at $CFG_DIR/api-key"
fi

# ─────────────────────────────────────────────────────────────────────
# Phase 4 — PATH hint + done banner
# ─────────────────────────────────────────────────────────────────────
if ! echo ":$PATH:" | grep -q ":$BIN_DIR:"; then
    echo
    err "$BIN_DIR is not in your PATH."
    err "  Add to your shell rc:  export PATH=\"\$HOME/.local/bin:\$PATH\""
fi

cat <<DONE

✓ dssh-whisper-api installed (lightweight, OpenRouter Whisper Turbo).

Manage with:
  dssh-whisper status     # check track + api-key presence
  dssh-whisper switch     # toggle api ↔ local
  dssh-whisper uninstall  # remove everything

The 3DS DSSH client invokes \`dssh-whisper-shim\` automatically when
you press START to record voice.  No daemon to start; the cloud handles
inference.  Want offline / private fallback?  Run install_whisper_dual.sh
to add the self-hosted whisper.cpp track alongside, then \`switch local\`.
DONE
