#!/usr/bin/env bash
# dssh-whisper-server installer (dual track) — sets up BOTH the
# OpenRouter API path AND the self-hosted whisper.cpp daemon, with the
# API as the default track and `dssh-whisper switch` to flip between
# them at runtime.
#
# Use this if you want offline / private fallback OR if you want to
# benchmark cloud-vs-local on your specific hardware.  Footprint
# ~600 MB (mostly the 466 MB small.zh model + 100 MB venv).
#
# For the lightweight cloud-only install, run install_whisper_api.sh
# instead — same CLI, no daemon, ~30 KB on disk.
#
# Run from a clone:
#   bash tools/install_whisper_dual.sh
#
# Or one-shot:
#   curl -fsSL https://raw.githubusercontent.com/Fishason/DSSH/main/tools/install_whisper_dual.sh | bash
#
# Idempotent: re-running upgrades scripts and restarts the daemon
# without re-downloading the model.
set -euo pipefail

INSTALL_DIR="$HOME/.local/share/dssh-whisper"
MODELS_DIR="$INSTALL_DIR/models"
CFG_DIR="$HOME/.config/dssh-whisper"
BIN_DIR="$HOME/.local/bin"
SVC_DIR="$HOME/.config/systemd/user"
SVC_NAME="dssh-whisper.service"
SVC_FILE="$SVC_DIR/$SVC_NAME"

if [ -n "${BASH_SOURCE[0]:-}" ] && [ -f "${BASH_SOURCE[0]}" ]; then
    SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
else
    SCRIPT_DIR=""
fi

c()   { printf '\033[%sm%s\033[0m\n' "$1" "$2"; }
log() { c '36' "▶ $*"; }
ok()  { c '32' "✓ $*"; }
err() { c '31' "✗ $*" >&2; }

# ─────────────────────────────────────────────────────────────────────
# Phase 1 — prerequisites (python3 + venv + systemd)
# ─────────────────────────────────────────────────────────────────────
log "checking prerequisites..."
if ! command -v python3 >/dev/null 2>&1; then
    err "python3 is required but not found."
    err "  Ubuntu / Debian:  sudo apt install -y python3 python3-pip python3-venv"
    exit 1
fi
ok "python3 $(python3 -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")')"

if ! python3 -c 'import venv' >/dev/null 2>&1; then
    err "python3-venv missing.  sudo apt install python3-venv"
    exit 1
fi
if ! command -v systemctl >/dev/null 2>&1; then
    err "systemctl not available.  This installer assumes systemd."
    err "  For cloud-only on non-systemd hosts, use install_whisper_api.sh."
    exit 1
fi

# ─────────────────────────────────────────────────────────────────────
# Phase 2 — venv + python deps for the LOCAL track
# ─────────────────────────────────────────────────────────────────────
mkdir -p "$INSTALL_DIR" "$CFG_DIR" "$BIN_DIR" "$SVC_DIR" "$MODELS_DIR"

if [ ! -d "$INSTALL_DIR/venv" ]; then
    log "creating venv at $INSTALL_DIR/venv ..."
    python3 -m venv "$INSTALL_DIR/venv"
fi

log "installing pywhispercpp + numpy (uses cached wheels if present) ..."
"$INSTALL_DIR/venv/bin/pip" install --quiet --upgrade pip
"$INSTALL_DIR/venv/bin/pip" install --quiet pywhispercpp numpy

# ─────────────────────────────────────────────────────────────────────
# Phase 3 — model download (idempotent)
# ─────────────────────────────────────────────────────────────────────
MODEL_FILE="$MODELS_DIR/ggml-small.bin"
if [ ! -f "$MODEL_FILE" ]; then
    log "downloading whisper small (multilingual, ~466 MB) — first run only ..."
    "$INSTALL_DIR/venv/bin/python" - <<PY
from pywhispercpp.model import Model
Model("small", models_dir="$MODELS_DIR")
PY
    ok "model cached at $MODEL_FILE"
else
    ok "model already cached at $MODEL_FILE ($(du -h "$MODEL_FILE" | cut -f1))"
fi

# ─────────────────────────────────────────────────────────────────────
# Phase 4 — drop daemon + shim + CLI wrapper
# ─────────────────────────────────────────────────────────────────────
log "installing daemon + shim + dssh-whisper CLI ..."

if [ -n "$SCRIPT_DIR" ] && [ -f "$SCRIPT_DIR/whisper_daemon.py" ]; then
    install -m 0755 "$SCRIPT_DIR/whisper_daemon.py" "$INSTALL_DIR/whisper_daemon.py"
    install -m 0755 "$SCRIPT_DIR/whisper_shim.py"   "$INSTALL_DIR/whisper_shim.py"
else
    err "Cannot locate whisper_daemon.py / whisper_shim.py next to this installer."
    err "  Run from a DSSH repo clone:"
    err "    git clone https://github.com/Fishason/DSSH /tmp/DSSH"
    err "    bash /tmp/DSSH/tools/install_whisper_dual.sh"
    exit 1
fi

cat > "$BIN_DIR/dssh-whisper" <<'WRAPPER'
#!/usr/bin/env bash
# Generated by install_whisper_dual.sh / install_whisper_api.sh.
# Manages the dssh-whisper voice-input track configuration plus the
# (optional) local self-hosted whisper.cpp daemon.
SVC=dssh-whisper.service
SVC_FILE="$HOME/.config/systemd/user/$SVC"
CFG="$HOME/.config/dssh-whisper"
TRACK_FILE="$CFG/track"
KEY_FILE="$CFG/api-key"

has_daemon()  { [ -f "$SVC_FILE" ]; }
cur_track()   { [ -f "$TRACK_FILE" ] && cat "$TRACK_FILE" || echo api; }
write_track() { mkdir -p "$CFG"; echo "$1" > "$TRACK_FILE"; }

ensure_daemon_for_local() {
    if [ "$1" = local ] && has_daemon; then
        if ! systemctl --user is-active --quiet "$SVC"; then
            echo "  starting local daemon..."
            systemctl --user start "$SVC" || {
                echo "  warning: could not start $SVC; check 'dssh-whisper logs'"
                return 1
            }
        fi
    elif [ "$1" = local ] && ! has_daemon; then
        echo "  warning: local track requires the dual install (install_whisper_dual.sh)."
        echo "           the API-only install has no local daemon to start."
    fi
}

case "${1:-status}" in
    start)
        if has_daemon; then systemctl --user start "$SVC"
        else echo "API-only install: no daemon to start (track=api uses OpenRouter)."; fi ;;
    stop|close)
        if has_daemon; then systemctl --user stop "$SVC"
        else echo "API-only install: no daemon to stop."; fi ;;
    restart)
        if has_daemon; then systemctl --user restart "$SVC"
        else echo "API-only install: no daemon to restart."; fi ;;
    status)
        echo "active track: $(cur_track)"
        if has_daemon; then
            echo "---"
            systemctl --user status "$SVC" --no-pager 2>&1 | head -10
        else
            echo "(API-only install — no local daemon)"
        fi
        if [ "$(cur_track)" = api ]; then
            if [ -f "$KEY_FILE" ]; then echo "api-key:  ✓ $KEY_FILE"
            else echo "api-key:  ✗ MISSING ($KEY_FILE)"; fi
        fi ;;
    switch)
        cur=$(cur_track)
        new="${2:-$([ "$cur" = api ] && echo local || echo api)}"
        case "$new" in api|local) ;; *) echo "usage: dssh-whisper switch [api|local]"; exit 1 ;; esac
        if [ "$new" = api ] && [ ! -f "$KEY_FILE" ]; then
            echo "✗ track=api requires an API key at $KEY_FILE"
            echo "  re-run install or write the key manually:  echo \"sk-or-...\" > $KEY_FILE && chmod 0600 $KEY_FILE"
            exit 1
        fi
        write_track "$new"
        echo "→ track: $new"
        ensure_daemon_for_local "$new" ;;
    logs)
        if has_daemon; then shift; journalctl --user -u "$SVC" -n 50 --no-pager "$@"
        else echo "API-only install: no daemon logs."; fi ;;
    uninstall)
        if has_daemon; then systemctl --user disable --now "$SVC" 2>/dev/null || true; fi
        rm -rf "$HOME/.local/share/dssh-whisper" \
               "$HOME/.config/dssh-whisper" \
               "$SVC_FILE" \
               "$HOME/.local/bin/dssh-whisper" \
               "$HOME/.local/bin/dssh-whisper-shim" \
               /tmp/dssh-whisper.sock
        if has_daemon; then systemctl --user daemon-reload; fi
        echo "✓ dssh-whisper uninstalled" ;;
    *)
        cat <<HELP
usage: dssh-whisper {start|stop|restart|status|switch|logs|uninstall}

  start      start the local daemon (dual install only; no-op for api-only)
  stop|close stop the local daemon
  restart    restart the local daemon
  status     show active track + daemon status + api-key presence
  switch     toggle / select track:  dssh-whisper switch [api|local]
  logs       tail the local daemon logs
  uninstall  remove all dssh-whisper files (irreversible)

The active "track" is one of:
  api    POST audio to OpenRouter Whisper Large V3 Turbo (~1 s, \$0.04/hr)
  local  forward to /tmp/dssh-whisper.sock (self-hosted whisper.cpp daemon)
HELP
        exit 1 ;;
esac
WRAPPER
chmod +x "$BIN_DIR/dssh-whisper"

ln -sf "$INSTALL_DIR/whisper_shim.py" "$BIN_DIR/dssh-whisper-shim"

# ─────────────────────────────────────────────────────────────────────
# Phase 5 — track config + API key (default: api, since it's faster)
# ─────────────────────────────────────────────────────────────────────
if [ ! -f "$CFG_DIR/track" ]; then
    echo "api" > "$CFG_DIR/track"
    ok "default track set to 'api' (use 'dssh-whisper switch local' to use the daemon)"
fi

if [ ! -f "$CFG_DIR/api-key" ]; then
    if [ -n "${OPENROUTER_API_KEY:-}" ]; then
        printf '%s\n' "$OPENROUTER_API_KEY" > "$CFG_DIR/api-key"
        chmod 0600 "$CFG_DIR/api-key"
        ok "api-key written from \$OPENROUTER_API_KEY"
    elif [ -t 0 ]; then
        echo
        echo "Need your OpenRouter API key (https://openrouter.ai/settings/keys)."
        echo "It looks like:  sk-or-v1-...."
        printf "Paste your key (or empty to skip — then track=local will be the only working option): "
        read -r KEY
        if [ -n "$KEY" ]; then
            printf '%s\n' "$KEY" > "$CFG_DIR/api-key"
            chmod 0600 "$CFG_DIR/api-key"
            ok "api-key saved at $CFG_DIR/api-key (chmod 0600)"
        else
            err "no key — auto-switching default track to 'local'"
            echo "local" > "$CFG_DIR/track"
        fi
    else
        err "no \$OPENROUTER_API_KEY in env and no terminal — defaulting to local track."
        echo "local" > "$CFG_DIR/track"
    fi
else
    ok "api-key already present at $CFG_DIR/api-key"
fi

# ─────────────────────────────────────────────────────────────────────
# Phase 6 — systemd user unit + linger
# ─────────────────────────────────────────────────────────────────────
log "writing systemd user unit ..."
cat > "$SVC_FILE" <<EOF
[Unit]
Description=DSSH whisper voice transcription daemon
After=default.target

[Service]
Type=simple
ExecStart=$INSTALL_DIR/venv/bin/python $INSTALL_DIR/whisper_daemon.py
Restart=on-failure
RestartSec=3
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=default.target
EOF

if command -v loginctl >/dev/null 2>&1; then
    if ! loginctl show-user "$USER" 2>/dev/null | grep -q '^Linger=yes'; then
        log "enabling linger so daemon survives SSH logout ..."
        if loginctl enable-linger "$USER" >/dev/null 2>&1; then
            ok "linger enabled"
        else
            err "loginctl enable-linger failed (likely needs sudo)."
            err "  Run once manually:  sudo loginctl enable-linger $USER"
            err "  Without linger the daemon exits when you SSH-logout."
        fi
    fi
fi

systemctl --user daemon-reload
systemctl --user enable --now "$SVC_NAME"

sleep 2
if systemctl --user is-active --quiet "$SVC_NAME"; then
    ok "$SVC_NAME is active; listening on /tmp/dssh-whisper.sock"
else
    err "$SVC_NAME failed to start; see:  dssh-whisper logs"
    exit 1
fi

# PATH hint
if ! echo ":$PATH:" | grep -q ":$BIN_DIR:"; then
    echo
    err "$BIN_DIR is not in your PATH."
    err "  Add to your shell rc:  export PATH=\"\$HOME/.local/bin:\$PATH\""
fi

cat <<DONE

✓ Dual-track install complete.

Default track: $(cat "$CFG_DIR/track")
Switch any time:  dssh-whisper switch api    (cloud, ~1s)
                  dssh-whisper switch local  (self-hosted, depends on server load)
                  dssh-whisper switch        (toggles)

Manage the local daemon:
  dssh-whisper status     # PID, memory, uptime + active track
  dssh-whisper stop       # pause local daemon (api still works)
  dssh-whisper start      # resume
  dssh-whisper logs -f    # follow daemon logs
  dssh-whisper uninstall  # remove everything

The 3DS DSSH client invokes \`dssh-whisper-shim\` over SSH automatically
when you press START to record voice.
DONE
