#pragma once
#include <stdint.h>

/*
 * Bitmap cell dimensions — single source of truth.  Both gen_font.py
 * (which writes source/font_data.c) and renderer.c (which blits the
 * bitmaps) must agree on these.
 *
 * To change cell size:
 *   1. Update CELL_W / CELL_H at the top of tools/gen_font.py to match.
 *   2. python3 tools/gen_font.py    (regenerates source/font_data.c)
 *   3. make
 *
 * 6×12 is the *native design size* of both Terminus and Zpix.  Going
 * smaller (e.g. 6×10) forces Pillow to interpolate-downscale the TTF
 * outlines, which turns 'm'/'M'/'W' into solid blobs (their internal
 * strokes can't fit in 5 pixels) and reduces Chinese characters to
 * mosaic noise.  We tried 6×10 and the visual quality was unusable, so
 * we kept 6×12 — losing 4 rows of screen space in exchange for legible
 * characters.  Top-screen layout is 66 cols × 20 rows.
 */
#define FA_CELL_W   6
#define FA_CELL_H  12

/* Auto-generated by tools/gen_font.py into source/font_data.c. */
extern const int      FONT_NGLYPHS;
extern const int      FONT_WIDE_NGLYPHS;

/* Narrow glyph bitmaps with 3-level grayscale antialiasing.
 *
 *   bytes [0          .. FA_CELL_H-1     ]  full-alpha layer (1bpp)
 *   bytes [FA_CELL_H   .. 2*FA_CELL_H-1  ]  half-alpha layer (1bpp)
 *   bytes [2*FA_CELL_H .. 3*FA_CELL_H-1  ]  quarter-alpha layer (1bpp)
 *
 * Each layer is a 1bpp bitmap (FA_CELL_W bits used per byte).  Pure
 * bitmap fonts (Terminus, Zpix at native size) render entirely into the
 * full layer with the half/quarter layers all-zero — zero-cost for those
 * fonts.  TTF text fonts (Liberation Mono / DejaVu) put edge pixels into
 * the half/quarter layers, giving smooth anti-aliased rendering at the
 * 6×12 cell size.  See draw_glyph in renderer.c. */
extern const uint8_t  font_glyphs[][3 * FA_CELL_H];
extern const int      FONT_UNICODE_MAP_LEN;
extern const uint32_t font_unicode_cps[];
extern const uint16_t font_unicode_idx[];

/* Wide glyph bitmaps (uint16_t row, FA_CELL_W*2 bits used). */
extern const uint16_t font_wide_glyphs[][FA_CELL_H];
extern const int      FONT_WIDE_MAP_LEN;
extern const uint32_t font_wide_cps[];
extern const uint16_t font_wide_idx[];

/* codepoint → glyph index. */
int font_glyph_index(uint32_t codepoint);       /* narrow: missing → '?' */
int font_wide_glyph_index(uint32_t codepoint);  /* wide:   missing → -1  */
int font_is_wide(uint32_t codepoint);           /* needs 2 cells? */
